### ISSUE TITLE
Bad interpolation for RdYlBu

### ISSUE THREAD

**Issue by Mixopteryx** [DrosteEffect/BrewerMap#1]
I recently tried to use the two-sided colormap RdYlBu via this function and noticed and that the color scale was not as smooth as I expected.

The following image illustrate the problem. Please note the lightening around 0.1 and 0.9. 
![image](https://cloud.githubusercontent.com/assets/1696312/9871544/bf218ef0-5b94-11e5-93e4-bde674d38256.png)

To the right i have used colormap(brewermap(128,'_RdYlBu')) and colormap(rgb2gray(brewermap(128,'_RdYlBu'))).
To the left I have used C=interp1(1:length(C),C,linspace(1,length(C),128)); where C is a matrix of the 11 colors I got directly from the RdYlBu colormap on colorbrewer2.org a while ago. 

My best suggestion is that this is related to that brewermaps interpolation is based on the 15 colors hard coded in and not the original 11 colors from the web. How have you got the 15 colors that are hard coded in the file?

This problems may also affect other divergent colormaps, I have not checked. The sequential colormaps I have tried seem fine.

**Comment by Mixopteryx** [comment]
For ease of access, Here is my code for my version of the colormap:

```
C=[ 165, 0, 38; 
    215, 48, 39; 
    244, 109, 67; 
    253, 174, 97; 
    254, 224, 144; 
    255, 255, 191; 
    224, 243, 248; 
    171, 217, 233; 
    116, 173, 209; 
    69, 117, 180; 
    49, 54, 149;
    ]/255; % 255 here to get number between 0 and one. 
% Reversing
C=C(end:-1:1,:);
% Interpolating
C=interp1(1:length(C),C,linspace(1,length(C),128));
```

**Comment by DrosteEffect** [comment]
Thank you for your observation and clear examples of this effect. I appreciate the support!

I agree that the fifteen colors is perhaps not as optimal as I originally thought, and will revise this in the following weeks.

The background of the fifteen colors is very simple: the colormaps as released by Cynthia Brewer on her website actually do use fifteen unique colors (for diverging, and thirteen unique colors for sequential schemes), but the colors used for one single colormap of eleven colors (the largest that she gives) are different to those colors used for a colormap of ten colors, etc. Simply put: Cynthia defined each colormap using a different subset of the total defined fifteen colors. This has several interesting side effects: it is not possible to exactly recreate any arbitrary smaller colormap using just the eleven colors of the largest colormap that she defined, because the smaller colormaps are defined using different colors. This is why my code uses indexing to pick the correct colors for colormaps smaller than eleven colors: this ensures that they exactly match those smaller colormaps that she gives on her website (as they are all subsets of those fifteen colors, not eleven).

It also raises the question: what are the "proper" values to interpolate for colormaps with more than eleven colors: those of her eleven color scheme, or her ten-color scheme? Perhaps some other interpolation or smoothing would be appropriate?

In my code I used all fifteen/thirteen colors that she defines for each scheme, and simply linearly interpolate between these to create larger colormaps, but as your point out this should be revised to avoid those color/shade bands. It seems a shame to throw away that data of those smaller colormaps, but perhaps interpolating the eleventh color colormap gives the smoothest and most expected result.

**Comment by Mixopteryx** [comment]
Thank you for explaining the 15 colors. Everything make more sense now. 

I expect that the problem with interpolation for with all 15 colors is that they are not equally spaced in "perceptual space". So, if you want to use all the colors I think the "proper" way will be to modify `map = interp1q((1:num).', rgb, num*xi + xi(end:-1:1));` to `map = interp1q(index.', rgb, num*xi + xi(end:-1:1));`, where `index` is a vector that represent the colors position in the perceptual space between the extreme colors. I do not know how to make this indexing. To me, it seems like interpolating with 11 colors is good enough, so finding the index is not worth the effort.

I think that using 11 colors for interpolation is best in all cases otherwise. That is because we have one color that is exact zero, which I like for the diverting maps. For the sequential maps, more colors is better. 

So my suggestion is: When more than 11/9 colors are requested for a diverging/sequential colormap, interpolate based on the map with 11/9 colors. (I have included sequential maps in the suggestion since I expect that they suffer from the same issue, although I have not observed the effect.)

Based on your description I think this can be attained by changing the output variable `num` of `cbSelect` to be the maximum number of colors in a hardcoded colormap, and doing the "downsample" with the maximum number step at line 187 before doing the interpolation.

If I find the time before you fix it I will try to implement it and send a pull request.

**Comment by DrosteEffect** [comment]
It required a few other changes due to the `num` value being quite integral to the map calculation, but I just uploaded a new version which uses only the 11/9  colors for larger colormaps, rather than the full 15/13. Here is an example using your suggested code `colormap(brewermap(128,'RdYlBu'))`

![example](https://cloud.githubusercontent.com/assets/10382992/9919826/93a90a5a-5ccf-11e5-9c88-35a57cbfa573.png)

**Comment by Mixopteryx** [comment]
I tried a couple colormaps with the new colormap and it looks perfect. Good work! 

Although the demo mode has become a bit confused: 
![image](https://cloud.githubusercontent.com/assets/1696312/9920482/bdf6c0b8-5cd4-11e5-8604-80a43a0ff683.png)
It seems like it picks the first colors 11 colors of the full palette for divergent maps, not the 11 used for the biggest map. The same applies to the sequential maps.

In this case I have no strong opinions if its right to show the whole palette or the biggest maps. It is also not a serius problem. Since the original problem is solved, I will close this issue now.
